# Generated by Django 3.1.7 on 2021-02-27 18:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.CharField(blank=True, default=core.models.increment_item_id_number, max_length=1000, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('prix_promo', models.FloatField(blank=True, null=True)),
                ('min_commande', models.IntegerField(blank=True, null=True)),
                ('max_commande', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type_item', models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('gar', 'garniture'), ('boi', 'Boisson'), ('san', 'Sandwich'), ('sau', 'Sauce'), ('pat', 'Pate')], max_length=3, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identification', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('num_tel', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('code_access', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(blank=True, default=core.models.increment_order_id_number, max_length=1000, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_de_demande', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ref_menu', models.CharField(blank=True, max_length=1000, null=True)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('montant_total', models.FloatField(default=0)),
                ('etat', models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.CharField(blank=True, default=core.models.increment_order_id, max_length=1000, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('not_orderd', models.BooleanField(default=True)),
                ('etat', models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True)),
                ('montant', models.FloatField(default=0)),
                ('mode_consommation', models.CharField(blank=True, choices=[('srp', 'Sur place'), ('emp', 'Emporter')], max_length=100, null=True)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, default=core.models.increment_menu_id_number, max_length=1000, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sauce', models.BooleanField(blank=True, null=True)),
                ('pate', models.BooleanField(blank=True, null=True)),
                ('garniture', models.BooleanField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to='core.menu'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
