# Generated by Django 3.1.7 on 2021-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210227_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('pat', 'Pate'), ('boi', 'Boisson'), ('san', 'Sandwich'), ('gar', 'garniture'), ('sup', 'Suppléments'), ('sau', 'Sauce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('arc', 'Archivé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('arc', 'Archivé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
