# Generated by Django 3.1.7 on 2021-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210227_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('sau', 'Sauce'), ('gar', 'garniture'), ('boi', 'Boisson'), ('san', 'Sandwich'), ('pat', 'Pate')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('arc', 'Archivé'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('arc', 'Archivé'), ('ann', 'Annulé')], max_length=3, null=True),
        ),
    ]
