# Generated by Django 3.0 on 2021-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210227_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('san', 'Sandwich'), ('pat', 'Pate'), ('gar', 'garniture'), ('boi', 'Boisson'), ('sup', 'Suppléments'), ('sau', 'Sauce')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_consommation',
            field=models.CharField(blank=True, choices=[('emp', 'Emporter'), ('srp', 'Sur place')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True),
        ),
    ]
