# Generated by Django 3.0 on 2021-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210227_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_formule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('gar', 'garniture'), ('san', 'Sandwich'), ('des', 'Dessert'), ('pat', 'Pate'), ('sau', 'Sauce'), ('boi', 'Boisson')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_consommation',
            field=models.CharField(blank=True, choices=[('emp', 'Emporter'), ('srp', 'Sur place')], max_length=100, null=True),
        ),
    ]
