# Generated by Django 3.0 on 2021-03-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210227_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeConso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conso', models.CharField(blank=True, choices=[('emp', 'Emporter'), ('sup', 'Sur place')], max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('for', 'Formule'), ('sup', 'Suppléments'), ('gar', 'garniture'), ('boi', 'Boisson'), ('des', 'Dessert'), ('san', 'Sandwich'), ('sau', 'Sauce'), ('pat', 'Pate')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('ann', 'Annulé'), ('enc', 'En cours'), ('arc', 'Archivé')], max_length=3, null=True),
        ),
    ]
