# Generated by Django 3.0 on 2021-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210301_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeconso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='modeconso',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('boi', 'Boisson'), ('san', 'Sandwich'), ('gar', 'garniture'), ('for', 'Formule'), ('sau', 'Sauce'), ('pat', 'Pate'), ('des', 'Dessert')], max_length=3, null=True),
        ),
    ]
