# Generated by Django 3.0 on 2021-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210301_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_menu',
            field=models.CharField(blank=True, choices=[('sau', 'Sauce'), ('sup', 'Suppléments'), ('pat', 'Pate'), ('des', 'Dessert'), ('for', 'Formule'), ('boi', 'Boisson'), ('gar', 'garniture'), ('san', 'Sandwich')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sau', 'Sauce'), ('sup', 'Suppléments'), ('pat', 'Pate'), ('des', 'Dessert'), ('for', 'Formule'), ('boi', 'Boisson'), ('gar', 'garniture'), ('san', 'Sandwich')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='modeconso',
            name='type_conso',
            field=models.CharField(blank=True, choices=[('srp', 'Sur place'), ('emp', 'Emporter')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('arc', 'Archivé'), ('ann', 'Annulé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_consommation',
            field=models.CharField(blank=True, choices=[('srp', 'Sur place'), ('emp', 'Emporter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('arc', 'Archivé'), ('ann', 'Annulé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
