# Generated by Django 3.0 on 2021-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210302_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('san', 'Sandwich'), ('gar', 'garniture'), ('for', 'Formule'), ('sau', 'Sauce'), ('pat', 'Pate'), ('des', 'Dessert'), ('boi', 'Boisson')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('arc', 'Archivé'), ('ann', 'Annulé'), ('fin', 'Finaliser'), ('val', 'Validé')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_menu',
            field=models.CharField(blank=True, choices=[('sup', 'Suppléments'), ('san', 'Sandwich'), ('gar', 'garniture'), ('for', 'Formule'), ('sau', 'Sauce'), ('pat', 'Pate'), ('des', 'Dessert'), ('boi', 'Boisson')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('arc', 'Archivé'), ('ann', 'Annulé'), ('fin', 'Finaliser'), ('val', 'Validé')], max_length=3, null=True),
        ),
    ]
