# Generated by Django 3.0 on 2021-03-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210316_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='step',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(blank=True, choices=[('sau', 'Sauce'), ('sup', 'Suppléments'), ('des', 'Dessert'), ('boi', 'Boisson'), ('pat', 'Pate'), ('for', 'Formule'), ('gar', 'garniture'), ('san', 'Sandwich')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Finaliser'), ('val', 'Validé'), ('ann', 'Annulé'), ('arc', 'Archivé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_menu',
            field=models.CharField(blank=True, choices=[('sau', 'Sauce'), ('sup', 'Suppléments'), ('des', 'Dessert'), ('boi', 'Boisson'), ('pat', 'Pate'), ('for', 'Formule'), ('gar', 'garniture'), ('san', 'Sandwich')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='etat',
            field=models.CharField(blank=True, choices=[('fin', 'Finaliser'), ('val', 'Validé'), ('ann', 'Annulé'), ('arc', 'Archivé'), ('enc', 'En cours')], max_length=3, null=True),
        ),
    ]
